# Generated by Django 4.1.1 on 2022-10-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_book_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='published',
            field=models.DateField(null=True),
        ),
    ]
